import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import ReactQueryProvider from './ReactQueryProvider'
import Header from '@/components/header/Header'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout(props: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<ReactQueryProvider>
				<body className={inter.className} style={{margin: 0}}>
					<Header />
					{props.children}
				</body>
			</ReactQueryProvider>
		</html>
	)
}
